#!/usr/bin/env python3
"""Generate docs/data_inventory.md from the nuclear data files themselves.

    MCSLAB_DATA=~/nuclear_data/endfb-viii.0-hdf5 ./venv/bin/python scripts/make_inventory.py

Everything in the output is read from the HDF5 files or computed from them
(through mcslab.nucdata and mcslab.xs). Nothing is typed in by hand except
the explanatory prose.
"""
import os
import sys

import h5py
import numpy as np

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)

from mcslab import xs                            # noqa: E402
from mcslab.nucdata import Library, file_sha256  # noqa: E402

NUCLIDES = ["H1", "Fe54", "Fe56", "Fe57", "Fe58", "W180", "W182", "W183", "W184",
            "W186", "Li6", "Li7", "Be9", "F19"]
E14 = 14.1e6
OUT = os.path.join(REPO, "docs", "data_inventory.md")
FIG_DIR = os.path.join(REPO, "docs", "figures")
# the cross-section figures written by scripts/plot_xs.py (other figures in
# docs/figures, e.g. the track animation, are not nuclear-data figures)
XS_FIGURES = ("fe56_total.png", "tritium_production.png", "be9_n2n.png", "overview.png")
SPECIAL = {301: "heating", 901: "heating-local", 444: "damage-energy",
           203: "(n,Xp)", 204: "(n,Xd)", 205: "(n,Xt)", 206: "(n,X3He)", 207: "(n,Xa)"}


def fmt(x, spec=".4g"):
    return "0" if x == 0 else format(x, spec)


def kinematic_threshold(q, awr):
    """Lab-frame threshold -Q (A+1)/A for Q < 0 (non-relativistic)."""
    return -q * (awr + 1.0) / awr if q < 0 else 0.0


def neutron_product_text(rx):
    parts = []
    for p in rx.neutron_products:
        y = (f"{p.yield_constant:g}" if p.yield_constant is not None
             else f"{p.yield_type} yield")
        parts.append(f"{y} x " + "; ".join(p.distributions))
    n_other = len(rx.products) - len(rx.neutron_products)
    if n_other:
        others = sorted({p.particle for p in rx.products if p.particle != "neutron"})
        parts.append(f"+{n_other} {'/'.join(others)}")
    return "<br>".join(parts) if parts else "none"


def attr_survey(lib):
    """All attribute names found on energy/<T> and reactions/*/<T>/xs datasets,
    plus URR table interpolation laws."""
    xs_attrs, e_attrs, urr = set(), set(), {}
    for name in NUCLIDES:
        with h5py.File(lib.nuclide_path(name), "r") as f:
            g = f[name]
            for T in g["energy"]:
                e_attrs |= set(g["energy"][T].attrs)
            for key in g["reactions"]:
                rg = g["reactions"][key]
                for T in rg:
                    if T.endswith("K"):
                        xs_attrs |= set(rg[T]["xs"].attrs)
            if "urr" in g and "294K" in g["urr"]:
                u = g["urr"]["294K"]
                e = u["energy"][()]
                urr[name] = (int(u.attrs["interpolation"]), float(e[0]), float(e[-1]))
    return xs_attrs, e_attrs, urr


def main():
    lib = Library.open()
    nucs = {n: lib.load(n) for n in NUCLIDES}
    xs_attrs, e_attrs, urr = attr_survey(lib)
    L = []
    w = L.append

    w("# Nuclear data inventory (Phase 2a)")
    w("")
    w(f"Generated by `scripts/make_inventory.py` from **{lib.label}** (official OpenMC HDF5 "
      "library, NJOY 2016.68 -> ACE -> HDF5), at **294 K**. Every number below is read from, "
      "or computed from, these files:")
    w("")
    w("| file | sha256 |")
    w("|---|---|")
    for n in NUCLIDES:
        w(f"| `neutron/{n}.h5` | `{file_sha256(lib.nuclide_path(n))}` |")
    w("")
    w("This inventory decides what Phase 2b (kinematics) and Phase 3 (heating, damage, "
      "gas production, TBR) must implement.")
    w("")

    # ------------------------------------------------------------------ findings
    w("## Key findings")
    w("")
    w("1. **MT 1 (total) is not stored** in any of the 14 files. MT 3 and MT 101 aren't "
      "either. OpenMC's HDF5 writer drops redundant reactions except a keep-list (MT 4, "
      "16, 103-107, 203-207, 301, 444, 901). mcslab defines the total as the sum of the "
      "non-redundant reactions, as OpenMC does.")
    w(f"2. **Interpolation.** The attributes found on any `reactions/*/<T>/xs` dataset are "
      f"{sorted(xs_attrs)}. On `energy/<T>` they are {sorted(e_attrs) or 'none'}. No "
      "interpolation law is stored for reaction cross sections. They are the "
      "NJOY-linearised pointwise data, which are interpolated lin-lin (ACE format manual "
      "LA-UR-19-29016, ESZ block). The reader refuses any other attribute. The only "
      "explicit laws in the files are on secondary distributions and URR tables.")
    w("3. **Grids.** All 14 grids are strictly increasing, with no duplicate points. Every "
      "reaction's first tabulated value (at `threshold_idx`) is exactly 0, so the "
      "threshold rule and lin-lin interpolation agree, and the summed total can be "
      "interpolated directly.")
    w("4. **Upper energy.** Fe and W are tabulated to 150 MeV. H1, Li, Be and F go to 20 MeV.")
    w("5. **Unresolved resonances.** URR probability tables are present for "
      + ", ".join(f"{k} ({a:.4g}-{b:.4g} eV, interpolation {i})" for k, (i, a, b) in urr.items())
      + ". mcslab does not use them yet, so the unresolved range is treated with smooth "
      "(infinite-dilution) cross sections. At 14.1 MeV this has no effect.")
    w("6. **Heating, damage and gas production are present for every nuclide** as redundant "
      "reactions (tables below). MT 301 and 901 are KERMA-type heating, and MT 444 is "
      "damage energy. All three are stored as energy x cross section in eV-barn, so "
      "dividing by sigma_t gives eV per collision. In OpenMC's convention, 301 "
      "(`heating`) excludes the energy of emitted photons, which are transported, and "
      "901 (`heating-local`) deposits it locally. MT 203-207 are gas-production cross "
      "sections in barns, multiplicity-weighted.")
    w("7. **Li-7 tritium production** is only available as the redundant MT 205. No "
      "non-redundant Li-7 reaction produces a triton explicitly. ENDF/B-VIII.0 represents "
      "Li-7(n,n't)alpha as the inelastic levels MT 52-82, whose residual breaks up "
      "(LR = 33 in ENDF). The HDF5 files do not keep the LR flag. The check below shows "
      "MT 205 = sum of MT 52-82 (all Li-7 levels above n1) to within ENDF rounding. MT 51 is a bound state (0.478 "
      "MeV) and is excluded. **Phase 3 TBR must score MT 205** (or MT 52-82 as a set) for "
      "Li-7, not a single (n,t) channel. For Li-6, MT 205 = MT 105 exactly.")
    w("")

    li7 = nucs["Li7"]
    comps = [m for m in range(52, 92) if m in li7.reactions]
    a = li7.summed_on_grid([205])
    b = li7.summed_on_grid(comps)
    d = np.abs(a - b)
    w(f"Li-7 check: max |MT205 - sum(MT {comps[0]}-{comps[-1]})| = {d.max():.3e} b over "
      f"{a.size} grid points (max relative {np.max(d[a > 0] / a[a > 0]):.2e}). "
      f"Including MT 51 gives a max difference of "
      f"{np.abs(a - li7.summed_on_grid([51] + comps)).max():.3f} b, so MT 51 is excluded.")
    w("")

    # ------------------------------------------------------------------ summary
    w("## Summary per nuclide")
    w("")
    w("| nuclide | AWR | grid points | E range (eV) | reactions (non-redundant) | URR | "
      "sigma_t(14.1 MeV) b |")
    w("|---|---|---|---|---|---|---|")
    for n in NUCLIDES:
        nu = nucs[n]
        w(f"| {n} | {nu.awr:.5f} | {nu.energy.size} | {nu.energy[0]:.0e} - "
          f"{nu.energy[-1]:.3g} | {len(nu.reactions)} ({len(nu.partial_mts)}) | "
          f"{'yes' if nu.has_urr else 'no'} | {xs.lookup_total(nu, E14):.5g} |")
    w("")

    w("## Heating, damage and gas production at 14.1 MeV")
    w("")
    w("MT 301/901/444 are shown as the stored value (eV-b) / sigma_t = eV per collision. "
      "MT 203-207 are cross sections in barns. A dash means the reaction is not in the "
      "file.")
    w("")
    w("| nuclide | 301 heating | 901 heating-local | 444 damage | 203 (n,Xp) | 204 (n,Xd) | "
      "205 (n,Xt) | 206 (n,X3He) | 207 (n,Xa) |")
    w("|---|---|---|---|---|---|---|---|---|")
    for n in NUCLIDES:
        nu = nucs[n]
        st = xs.lookup_total(nu, E14)
        cells = []
        for mt in (301, 901, 444):
            cells.append(f"{xs.lookup(nu, mt, E14) / st / 1e6:.4g} MeV" if mt in nu.reactions
                         else "-")
        for mt in (203, 204, 205, 206, 207):
            cells.append(fmt(xs.lookup(nu, mt, E14)) if mt in nu.reactions else "-")
        w(f"| {n} | " + " | ".join(cells) + " |")
    w("")

    figures = [fn for fn in sorted(XS_FIGURES) if os.path.isfile(os.path.join(FIG_DIR, fn))]
    if figures:
        w("## Figures")
        w("")
        for fn in figures:
            w(f"![{fn}](figures/{fn})")
            w("")

    # ------------------------------------------------------------------ per nuclide
    w("## Reactions per nuclide")
    w("")
    w("Columns:")
    w("- **grid thr**: the first tabulated energy (at `threshold_idx`).")
    w("- **kin thr**: -Q(A+1)/A for Q < 0.")
    w("- **frame**: the frame of the secondary distributions (CM or lab).")
    w("- **outgoing neutrons**: yield x distribution type.")
    w("")
    w("For redundant reactions, Q is stored as 0 and carries no meaning.")
    w("")
    for n in NUCLIDES:
        nu = nucs[n]
        w(f"### {n}  (Z={nu.Z}, A={nu.A}, AWR={nu.awr:.5f}, {nu.energy.size} points)")
        w("")
        w("| MT | label | redundant | Q (MeV) | grid thr (MeV) | kin thr (MeV) | "
          "sigma(14.1 MeV) b | frame | outgoing neutrons |")
        w("|---|---|---|---|---|---|---|---|---|")
        for mt in sorted(nu.reactions):
            rx = nu.reactions[mt]
            red = "yes" if rx.redundant else ""
            if mt in SPECIAL and mt in (301, 901, 444):
                s14 = f"{xs.lookup(nu, mt, E14):.4g} eV-b"
            else:
                s14 = fmt(xs.lookup(nu, mt, E14))
            q = "" if rx.redundant else fmt(rx.q_value / 1e6, ".6g")
            kin = (fmt(kinematic_threshold(rx.q_value, nu.awr) / 1e6, ".6g")
                   if (not rx.redundant and rx.q_value < 0) else "")
            thr = fmt(nu.threshold_energy(mt) / 1e6, ".6g")
            frame = "CM" if rx.center_of_mass else "lab"
            w(f"| {mt} | {rx.label} | {red} | {q} | {thr} | {kin} | {s14} | {frame} | "
              f"{neutron_product_text(rx)} |")
        w("")

    with open(OUT, "w") as fh:
        fh.write("\n".join(L).rstrip() + "\n")
    print(f"wrote {os.path.relpath(OUT, REPO)}")


if __name__ == "__main__":
    main()
